# Wrapper generato automaticamente per il comando New-ModuleManifest

function New-ModuleManifest {
    param (
        [String] $Path,
        [Object[]] $NestedModules,
        [Guid] $Guid,
        [String] $Author,
        [String] $CompanyName,
        [String] $Copyright,
        [String] $RootModule,
        [Version] $ModuleVersion,
        [String] $Description,
        [ProcessorArchitecture] $ProcessorArchitecture,
        [Version] $PowerShellVersion,
        [Version] $ClrVersion,
        [Version] $DotNetFrameworkVersion,
        [String] $PowerShellHostName,
        [Version] $PowerShellHostVersion,
        [Object[]] $RequiredModules,
        [String[]] $TypesToProcess,
        [String[]] $FormatsToProcess,
        [String[]] $ScriptsToProcess,
        [String[]] $RequiredAssemblies,
        [String[]] $FileList,
        [Object[]] $ModuleList,
        [String[]] $FunctionsToExport,
        [String[]] $AliasesToExport,
        [String[]] $VariablesToExport,
        [String[]] $CmdletsToExport,
        [String[]] $DscResourcesToExport,
        [String[]] $CompatiblePSEditions,
        [Object] $PrivateData,
        [String[]] $Tags,
        [Uri] $ProjectUri,
        [Uri] $LicenseUri,
        [Uri] $IconUri,
        [String] $ReleaseNotes,
        [String] $Prerelease,
        [SwitchParameter] $RequireLicenseAcceptance,
        [String[]] $ExternalModuleDependencies,
        [String] $HelpInfoUri,
        [SwitchParameter] $PassThru,
        [String] $DefaultCommandPrefix,
        [SwitchParameter] $Verbose,
        [SwitchParameter] $Debug,
        [ActionPreference] $ErrorAction,
        [ActionPreference] $WarningAction,
        [ActionPreference] $InformationAction,
        [ActionPreference] $ProgressAction,
        [String] $ErrorVariable,
        [String] $WarningVariable,
        [String] $InformationVariable,
        [String] $OutVariable,
        [Int32] $OutBuffer,
        [String] $PipelineVariable,
        [SwitchParameter] $WhatIf,
        [SwitchParameter] $Confirm
    )

    # Inserisci qui la logica per utilizzare il comando New-ModuleManifest
    # Ad esempio:
    $result = &New-ModuleManifest @PSBoundParameters
    return $result
}
